#!/usr/bin/env node
'use strict';
/**
 * Builds the static GitHub Pages version into docs/.
 *
 * GitHub Pages can't run the Node server, so this bundles the league + game engine
 * (server/*.js) into docs/core.js and adds pages/local.js, which answers the app's
 * /api calls inside the browser and saves the league in IndexedDB. The result is a
 * fully static, installable (Add to Home Screen) app.
 *
 *   npm run build:pages
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const root = path.join(__dirname, '..');
const out = path.join(root, 'docs');
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');

// ------------------------------------------------------------ core bundle
const modules = ['engine', 'schedule', 'players', 'league', 'routes'];
const shims = {
  events: `class EventEmitter {
    constructor() { this._ev = {}; }
    on(e, fn) { (this._ev[e] = this._ev[e] || []).push(fn); return this; }
    off(e, fn) { this._ev[e] = (this._ev[e] || []).filter((f) => f !== fn); return this; }
    emit(e, ...a) { (this._ev[e] || []).slice().forEach((fn) => fn(...a)); return true; }
  }
  module.exports = { EventEmitter };`,
  path: 'module.exports = { join: (...a) => a.join("/") };',
  fs: 'module.exports = {};',
  crypto: 'module.exports = {};',
};
let bundle = `/* Generated by scripts/build-pages.js — do not edit. Source: server/*.js */
(function () {
  'use strict';
  var process = { env: {} };
  var defs = {};
  var cache = {};
  function req(name) {
    var key = name.replace(/^\\.\\//, '');
    if (cache[key]) return cache[key].exports;
    if (!defs[key]) throw new Error('Module not bundled: ' + name);
    var module = { exports: {} };
    cache[key] = module;
    defs[key](module, module.exports, req, '');
    return module.exports;
  }
`;
for (const [name, src] of Object.entries(shims)) {
  bundle += `  defs[${JSON.stringify(name)}] = function (module, exports, require, __dirname) {\n${src}\n};\n`;
}
for (const m of modules) {
  bundle += `  defs[${JSON.stringify(m)}] = function (module, exports, require, __dirname) {\n${read(`server/${m}.js`)}\n};\n`;
}
bundle += `  window.FHCore = { engine: req('engine'), players: req('players'), league: req('league'), routes: req('routes') };
  window.FH_PLAYERS_CSV = ${JSON.stringify(read('data/players.csv'))};
})();
`;

// ------------------------------------------------------------ write docs/
fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(path.join(out, 'icons'), { recursive: true });
const files = {};
files['core.js'] = bundle;
files['local.js'] = read('pages/local.js');
for (const f of ['app.js', 'styles.css', 'manifest.webmanifest']) files[f] = read(`public/${f}`);
for (const f of fs.readdirSync(path.join(root, 'public', 'icons'))) files[`icons/${f}`] = fs.readFileSync(path.join(root, 'public', 'icons', f));

const version = crypto.createHash('sha256').update(Object.values(files).map((x) => (Buffer.isBuffer(x) ? x : Buffer.from(x))).reduce((a, b) => Buffer.concat([a, b]))).digest('hex').slice(0, 12);

let html = read('public/index.html');
if (!html.includes('<!-- local-runtime -->')) throw new Error('index.html is missing the <!-- local-runtime --> marker');
html = html.replace('<!-- local-runtime -->', `<script src="core.js?v=${version}"></script>
  <script src="local.js?v=${version}"></script>
  <script>
    if ('serviceWorker' in navigator) {
      var hadController = !!navigator.serviceWorker.controller;
      navigator.serviceWorker.register('sw.js').catch(function () {});
      navigator.serviceWorker.addEventListener('controllerchange', function () { if (hadController) location.reload(); });
    }
  </script>`)
  .replace('src="app.js"', `src="app.js?v=${version}"`)
  .replace('href="styles.css"', `href="styles.css?v=${version}"`);
files['index.html'] = html;

// Offline support: precache the app shell; a new build = new cache version.
const shell = ['./', 'index.html', ...Object.keys(files).filter((f) => f !== 'index.html')];
files['sw.js'] = `/* Generated by scripts/build-pages.js */
const CACHE = 'fantasy-hoops-${version}';
const SHELL = ${JSON.stringify(shell)};
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  const url = new URL(e.request.url);
  if (url.origin !== location.origin) return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then((hit) => hit || fetch(e.request)));
});
`;
files['.nojekyll'] = '';

for (const [name, data] of Object.entries(files)) fs.writeFileSync(path.join(out, name), data);
console.log(`Built docs/ (version ${version}): ${Object.keys(files).length} files, core.js ${(bundle.length / 1024).toFixed(0)} KB`);
