#!/usr/bin/env python3
"""Rebuild docs/players.js from the static NBA player list in the nba_api project.

Usage: python3 scripts/update-players.py
"""
import ast
import json
import pathlib
import re
import urllib.request

SOURCE = "https://raw.githubusercontent.com/swar/nba_api/master/src/nba_api/stats/library/data.py"
OUT = pathlib.Path(__file__).resolve().parent.parent / "docs" / "players.js"

src = urllib.request.urlopen(SOURCE, timeout=60).read().decode("utf-8")
block = re.search(r"^players = (\[.*?^\])", src, re.S | re.M).group(1)
rows = ast.literal_eval(block.replace("True", "1").replace("False", "0"))

# [nba id, full name, active (1/0)]; active players first, then alphabetical by last name
rows.sort(key=lambda r: (-r[4], r[1].lower(), r[2].lower()))
players = [[r[0], r[3], r[4]] for r in rows]

OUT.write_text(
    "// Generated by scripts/update-players.py (source: nba_api static player list)\n"
    "window.NBA_PLAYERS = " + json.dumps(players, ensure_ascii=False, separators=(",", ":")) + ";\n",
    encoding="utf-8",
)
print(f"wrote {len(players)} players ({sum(p[2] for p in players)} active) to {OUT}")
